sudo: required
dist: trusty
language: generic
python: 
  - "2.7"
services:
- docker
env:
  global:
  - SHA=$(git rev-parse HEAD)
  - secure: L74PVryf/NB7WfE4kqrGb3K0Sydj//f1PGhilrRRRi+wYhsUvxT/pOlL5QySeaT6WhYZFHOSar4Ud0PS98JB1xM+DZF3tfjeCb5NJ+OfYIvJKOLTJ1HQMjIbqXlytv+xdGort4eVnLAu94Azkdm8X9Gt2LSZ99SvIGM9jvhKDS/IkoyFPCijufGoLfSFsUOkyni8YV1KolFsqlXX4M2yET2PIFugU+DsAGWiY1li/3itTat1UhEBObMT8LnDXIOVxjdYiLRNzImmq3d0JFlS03KWFSdVK617DH2wRtro3Y3ZHrMU7wuq76ccwd97Unct0rMP2kDS4CZjwxP5tyM9475O/NwVBBv6/7lt6l+K31LdZ57upvCZCESx8cw01krm5xfOFSGngW0qGKL6DLdV6i/hYb1ihFMxTRD0wojbyOg41n0Oysf5cmwUpiXewfnKA6stD9kVDo2Rdb7Qq9VmROgqOeMBFUYOAEzBcUo1CfFo+8BBQhr2KQGyXAghAefmG4ts/xcwHfQWZ/kV+6pqFT3+V+kHrv9Au46B5WPZPh9enixPfbvx3x7CCpJhmbl8jH0OMV48L8+qUhjHRsnF7VQWO+vPDQnex92hqnyei515zO9XKwd5HmeMMccv8pwZFlEa7mrWU+bGoEHTLOLpsyrh8phiLfDjkqJsyaeKzCI=
  - secure: b9OaoOjeuKLslKUn3Hks+2+LkYBBzFAWRotLYdjLN8ALFdANhMsNshGMQrcEVrYbdqkHfyijWaN29aO4SuUPvr1USiBhl3Bpj4Fd49dxwc8boV0lu/zjvO2L9obT0PjxZIJi1xB4NnwOx2lAT2aVX4/L1RbybH7+7/E9B3p4J/447zG0MiKw9rzlg4+dKPGKYSqN/6l+uw+HAUOzsf+WCr406096/j8jqUnOMEiBv8mekBOffMm1PpS5tQlu/2FFuYM/cl19pcOZHKyrDU50hReaEL41GeBTXg5Ecv/AOTpfOT0eBxmAxlihJLG1F1TNWIwzdCC8kO8vTwcjYitGHSEax9xnoSZypg001yvHr6Ik0ayYuDG+6+l+86AHttw36+V3pTF5asHLK3G+RenteXp07/8UwJlNWlsVHMBZo7SnbrxkV+bIUTKk/LaC/Tug+B17AqUQ8eNeIoooD0ttCjJZcJO92R+bWpCWBsGWkRYuv8qmT+ipQkeHauVNq7T/FgoMNUnUNJdXMrPYkVZFZ/srFTbIJFn4ZPJzJ9vdgUUSy8m8UbYmzAvW56R/XnzT1+0t8tInoHo59imfOQn/XFBMV/iWsmVngWbXPxjK9gG9lhlahFr3ryJ+4n5VLcDy26EnT0d4wcr2b4YmtoG4WBYpuEO5oiZ03A/TpZcXShU=
before_install:
  - pip install awscli --user 
  - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
  - curl -o aws-iam-authenticator.sha256 https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator.sha256
  - openssl sha1 -sha256 aws-iam-authenticator
  - chmod +x ./aws-iam-authenticator
  - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$HOME/bin:$PATH
  - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
  - aws eks --region us-west-2 update-kubeconfig --name multi-k8s --role-arn arn:aws:iam::894511344406:user/Administrator
  - export PATH=$PATH:$HOME/.local/bin
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
