apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"alb-ingress-controller"},"name":"alb-ingress-controller","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/name":"alb-ingress-controller"}},"template":{"metadata":{"labels":{"app.kubernetes.io/name":"alb-ingress-controller"}},"spec":{"containers":[{"args":["--ingress-class=alb"],"image":"docker.io/amazon/aws-alb-ingress-controller:v1.1.2","name":"alb-ingress-controller"}],"serviceAccountName":"alb-ingress-controller"}}}}
  creationTimestamp: "2019-07-18T21:17:07Z"
  generation: 1
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
  resourceVersion: "16308"
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/alb-ingress-controller
  uid: 661cf191-a9a1-11e9-9932-02cb8f3cced4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: alb-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: alb-ingress-controller
    spec:
      containers:
      - args:
        - --ingress-class=alb
        - --cluster-name=multi-k8s
        - --aws-vpc-id=vpc-03cb05a1f33b90454
        - --aws-region=us-west-2
        image: docker.io/amazon/aws-alb-ingress-controller:v1.1.2
        imagePullPolicy: IfNotPresent
        name: alb-ingress-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alb-ingress-controller
      serviceAccountName: alb-ingress-controller
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-07-18T21:17:07Z"
    lastUpdateTime: "2019-07-18T21:17:07Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2019-07-18T21:17:07Z"
    lastUpdateTime: "2019-07-18T21:17:07Z"
    message: ReplicaSet "alb-ingress-controller-9466cd458" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1